ARG WEBGRIND_VERSION=latest
FROM clue/webgrind:${WEBGRIND_VERSION}

#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}

EXPOSE 15777



